server:
  name: video_service  # 服务名称
  port: :10002
  address: 127.0.0.1:10002  # 服务地址


mysql:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: tiny_tiktok


etcd:
  address: 127.0.0.1:2379

oss:
  bucketName: tiny-tiktok
  endpoint: https://oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI5t8nzWHJ1tm92ZPUKods
  accessKeySecret: secret

rabbitMQ:
  user: guest
  password: guest
  address: localhost:5672